<script setup lang="ts">
import { Head, Link, useForm } from '@inertiajs/vue3';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';

type Utility = { id:string; type:string; type_label:string; billed_from:string; billed_to:string; paid_at:string; total_amount:number; business_percentage:string; household_percentage:string; business_amount:number; household_amount:number; physical_consumption:string|null; physical_consumption_unit:string|null; reference:string|null };
type Rate = { id:string; type:string; type_label:string; suggested_rate:number|null; manual_rate:number|null; effective_rate:number; calculation_base_quantity:string; method:string; override_reason:string|null };
type Variance = { id:string; cost_type:string; actual_amount:number; allocated_amount:number; variance_amount:number };
type Period = { id:string; label:string; status:string; status_label:string; processed_flour_quantity:string; utilities:Utility[]; rates:Rate[]; variances:Variance[] };
const props = defineProps<{ period:Period; canClose:boolean; canReopen:boolean }>();
const closeForm = useForm({});
const reopenForm = useForm({ reason:'' });
const money = (value:number|null) => value === null ? '—' : new Intl.NumberFormat('es-CO', { style:'currency', currency:'COP', maximumFractionDigits:0 }).format(value);
const typeLabel = (type:string) => ({ electricity:'Electricidad', gas:'Gas', labor:'Mano de obra' }[type] ?? type);
</script>

<template>
    <Head :title="`Costos ${period.label}`" />
    <main class="flex flex-1 flex-col gap-5 p-4 md:p-6">
        <header class="flex flex-wrap justify-between gap-3"><div><p class="text-sm text-muted-foreground">Periodo de costos</p><h1 class="text-2xl font-semibold">{{ period.label }}</h1><p class="text-sm text-muted-foreground">{{ period.status_label }} · {{ period.processed_flour_quantity }} kg procesados</p></div><div class="flex gap-2"><Button v-if="canClose && period.status === 'open'" :disabled="closeForm.processing" @click="closeForm.post(`/cost-periods/${period.id}/close`)">Cerrar y conciliar</Button><Button variant="outline" as-child><Link href="/cost-periods">Volver</Link></Button></div></header>
        <section class="grid gap-4 lg:grid-cols-2"><article v-for="utility in period.utilities" :key="utility.id" class="rounded-xl border bg-card p-4"><h2 class="font-semibold">{{ utility.type_label }}</h2><p class="text-xs text-muted-foreground">{{ utility.billed_from }} a {{ utility.billed_to }} · pagada {{ utility.paid_at }}</p><div class="mt-4 grid grid-cols-3 gap-3 text-sm"><div><p class="text-xs text-muted-foreground">Total</p><strong>{{ money(utility.total_amount) }}</strong></div><div><p class="text-xs text-muted-foreground">Negocio {{ utility.business_percentage }} %</p><strong>{{ money(utility.business_amount) }}</strong></div><div><p class="text-xs text-muted-foreground">Hogar {{ utility.household_percentage }} %</p><strong>{{ money(utility.household_amount) }}</strong></div></div><p v-if="utility.physical_consumption" class="mt-3 text-xs">Consumo: {{ utility.physical_consumption }} {{ utility.physical_consumption_unit }}</p></article></section>
        <section class="overflow-x-auto rounded-xl border bg-card"><table class="w-full text-sm"><thead class="border-b bg-muted/40 text-left"><tr><th class="px-4 py-3">Costo</th><th class="px-4 py-3">Base anterior</th><th class="px-4 py-3">Sugerida</th><th class="px-4 py-3">Manual</th><th class="px-4 py-3">Efectiva</th><th class="px-4 py-3">Método</th></tr></thead><tbody class="divide-y"><tr v-for="rate in period.rates" :key="rate.id"><td class="px-4 py-3 font-medium">{{ rate.type_label }}</td><td class="px-4 py-3">{{ rate.calculation_base_quantity }} kg</td><td class="px-4 py-3">{{ money(rate.suggested_rate) }}</td><td class="px-4 py-3">{{ money(rate.manual_rate) }}</td><td class="px-4 py-3 font-semibold">{{ money(rate.effective_rate) }}/kg</td><td class="px-4 py-3">{{ rate.method === 'manual' ? 'Manual' : 'Sugerida' }}</td></tr></tbody></table></section>
        <section v-if="period.variances.length" class="overflow-x-auto rounded-xl border bg-card"><div class="p-4"><h2 class="font-semibold">Conciliación del cierre</h2><p class="text-sm text-muted-foreground">Variación = costo real menos costo aplicado a las producciones.</p></div><table class="w-full text-sm"><thead class="border-y bg-muted/40 text-left"><tr><th class="px-4 py-3">Costo</th><th class="px-4 py-3">Real</th><th class="px-4 py-3">Aplicado</th><th class="px-4 py-3">Variación</th></tr></thead><tbody class="divide-y"><tr v-for="variance in period.variances" :key="variance.id"><td class="px-4 py-3">{{ typeLabel(variance.cost_type) }}</td><td class="px-4 py-3">{{ money(variance.actual_amount) }}</td><td class="px-4 py-3">{{ money(variance.allocated_amount) }}</td><td class="px-4 py-3 font-semibold" :class="variance.variance_amount > 0 ? 'text-destructive' : ''">{{ money(variance.variance_amount) }}</td></tr></tbody></table></section>
        <form v-if="canReopen && period.status === 'closed'" class="grid max-w-xl gap-3 rounded-xl border border-amber-300 p-4" @submit.prevent="reopenForm.post(`/cost-periods/${period.id}/reopen`)"><h2 class="font-semibold">Reabrir periodo</h2><p class="text-sm text-muted-foreground">La conciliación contable será revertida y deberá cerrarse nuevamente.</p><Input v-model="reopenForm.reason" required placeholder="Motivo de reapertura"/><Button type="submit" variant="outline" :disabled="reopenForm.processing">Reabrir</Button></form>
    </main>
</template>
