<script setup lang="ts">
import { Head, Link, router } from '@inertiajs/vue3';
import { Button } from '@/components/ui/button';
const props = defineProps<{ month:string; metrics:any; accounts:any[]; categories:any[]; people:any[]; filters:any; movements:{data:any[]}; incomeRecords:any[]; expenseRecords:any[]; payables:any[]; canManage:boolean }>();
const money = (value:number) => new Intl.NumberFormat('es-CO', { style:'currency', currency:'COP', maximumFractionDigits:0 }).format(value || 0);
const changeMonth = (event:Event) => router.get('/finance', { month:(event.target as HTMLInputElement).value }, { preserveState:true });
</script>

<template>
    <Head title="Finanzas del negocio" />
    <main class="flex flex-1 flex-col gap-5 p-4 md:p-6">
        <header class="flex flex-wrap items-end justify-between gap-3"><div><h1 class="text-2xl font-semibold">Finanzas del negocio</h1><p class="text-sm text-muted-foreground">Flujo de efectivo y resultado económico se muestran por separado.</p></div><div class="flex gap-2"><input :value="month" type="month" class="h-9 rounded-md border bg-transparent px-3 text-sm" @change="changeMonth" /><Button v-if="canManage" as-child><Link href="/finance/records/create">Registrar movimiento</Link></Button></div></header>
        <section class="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><article class="rounded-xl border bg-card p-4"><small>Flujo neto</small><p class="text-xl font-semibold" :class="metrics.cash_flow < 0 ? 'text-destructive' : ''">{{ money(metrics.cash_flow) }}</p><p class="text-xs text-muted-foreground">Entradas {{ money(metrics.cash_in) }} · salidas {{ money(metrics.cash_out) }}</p></article><article class="rounded-xl border bg-card p-4"><small>Resultado {{ month === new Date().toISOString().slice(0,7) ? 'provisional' : '' }}</small><p class="text-xl font-semibold" :class="metrics.profit < 0 ? 'text-destructive' : ''">{{ money(metrics.profit) }}</p><p class="text-xs text-muted-foreground">Ingresos {{ money(metrics.revenue) }} · costos/gastos {{ money(metrics.expenses) }}</p></article><article class="rounded-xl border bg-card p-4"><small>Cuentas por cobrar</small><p class="text-xl font-semibold">{{ money(metrics.receivables) }}</p><Link href="/receivables" class="text-xs text-amber-700">Ver cartera</Link></article><article class="rounded-xl border bg-card p-4"><small>Cuentas por pagar</small><p class="text-xl font-semibold">{{ money(metrics.payables) }}</p></article></section>
        <section class="rounded-xl border bg-card p-4"><h2 class="font-semibold">Saldos por cuenta</h2><div class="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><div v-for="account in accounts" :key="account.id" class="rounded-lg bg-muted/40 p-3 text-sm"><p>{{ account.code }} · {{ account.name }}</p><strong>{{ money(account.balance) }}</strong></div></div></section>
        <section v-if="payables.length" class="overflow-x-auto rounded-xl border bg-card"><h2 class="p-4 font-semibold">Obligaciones pendientes</h2><table class="w-full text-sm"><thead class="border-y bg-muted/40 text-left"><tr><th class="px-4 py-3">Documento</th><th class="px-4 py-3">Tercero</th><th class="px-4 py-3">Vence</th><th class="px-4 py-3">Saldo</th><th></th></tr></thead><tbody class="divide-y"><tr v-for="item in payables" :key="item.id"><td class="px-4 py-3">{{ item.document_number }}</td><td class="px-4 py-3">{{ item.person }}</td><td class="px-4 py-3">{{ item.due_at || 'Sin fecha' }}</td><td class="px-4 py-3">{{ money(item.balance_amount) }}</td><td class="px-4 py-3 text-right"><Link v-if="canManage" :href="`/finance/payables/${item.id}/payments/create`" class="text-amber-700">Pagar</Link></td></tr></tbody></table></section>
        <section class="grid gap-4 lg:grid-cols-2"><article v-for="group in [{title:'Ingresos administrativos',items:incomeRecords},{title:'Gastos administrativos',items:expenseRecords}]" :key="group.title" class="rounded-xl border bg-card"><h2 class="p-4 font-semibold">{{ group.title }}</h2><div class="divide-y"><div v-for="item in group.items" :key="item.id" class="flex justify-between gap-3 p-4 text-sm"><div><strong>{{ item.document_number }} · {{ item.category }}</strong><p class="text-muted-foreground">{{ item.description }} · {{ item.status }}</p></div><div class="text-right"><strong>{{ money(item.total_amount) }}</strong><p class="text-xs text-muted-foreground">Saldo {{ money(item.balance_amount) }}</p></div></div><p v-if="!group.items.length" class="p-6 text-sm text-muted-foreground">Sin movimientos en el mes.</p></div></article></section>
        <section class="overflow-x-auto rounded-xl border bg-card"><div class="p-4"><h2 class="font-semibold">Trazabilidad contable</h2><form method="get" action="/finance" class="mt-3 flex flex-wrap gap-2"><input type="hidden" name="month" :value="month"/><select name="account_id" :value="filters.account_id" class="h-9 rounded-md border bg-transparent px-3 text-sm"><option value="">Todas las cuentas</option><option v-for="account in accounts" :key="account.id" :value="account.id">{{ account.code }} · {{ account.name }}</option></select><select name="category_id" :value="filters.category_id" class="h-9 rounded-md border bg-transparent px-3 text-sm"><option value="">Todas las categorías</option><option v-for="category in categories" :key="category.id" :value="category.id">{{ category.name }}</option></select><select name="person_id" :value="filters.person_id" class="h-9 rounded-md border bg-transparent px-3 text-sm"><option value="">Todos los terceros</option><option v-for="person in people" :key="person.id" :value="person.id">{{ person.name }}</option></select><Button type="submit" variant="outline">Filtrar</Button></form></div><table class="w-full text-sm"><thead class="border-y bg-muted/40 text-left"><tr><th class="px-4 py-3">Fecha / documento</th><th class="px-4 py-3">Cuenta</th><th class="px-4 py-3">Tercero</th><th class="px-4 py-3">Débito</th><th class="px-4 py-3">Crédito</th></tr></thead><tbody class="divide-y"><tr v-for="line in movements.data" :key="line.id"><td class="px-4 py-3"><strong>{{ line.document }}</strong><small class="block text-muted-foreground">{{ line.date }} · {{ line.entry_description }}</small></td><td class="px-4 py-3">{{ line.account }}</td><td class="px-4 py-3">{{ line.person || '—' }}</td><td class="px-4 py-3">{{ money(line.debit) }}</td><td class="px-4 py-3">{{ money(line.credit) }}</td></tr></tbody></table></section>
    </main>
</template>
