<script setup lang="ts">
import { Head, Link, router } from '@inertiajs/vue3';
import { reactive } from 'vue';
import { Button } from '@/components/ui/button';

const props = defineProps<{ filters:any; permissions:{financial:boolean;operational:boolean;household:boolean}; business:any|null; margins:any[]; obligations:any|null; production:any|null; inventory:any|null; household:any|null; presentations:any[]; people:any[] }>();
const filter = reactive({ ...props.filters });
const money = (value:number) => new Intl.NumberFormat('es-CO', { style:'currency', currency:'COP', maximumFractionDigits:0 }).format(value || 0);
const number = (value:number, digits=2) => new Intl.NumberFormat('es-CO', { maximumFractionDigits:digits }).format(value || 0);
const apply = () => router.get('/reports', filter, { preserveState:true, replace:true });
const resultLabel = (value:number) => value > 0 ? 'Ganancia' : value < 0 ? 'Pérdida' : 'Equilibrio';
</script>

<template>
    <Head title="Reportes" />
    <main class="flex flex-1 flex-col gap-5 p-4 md:p-6">
        <header><h1 class="text-2xl font-semibold">Tableros y reportes</h1><p class="text-sm text-muted-foreground">Cada cifra se deriva de pagos, asientos, inventario o documentos operativos confirmados.</p></header>
        <form class="flex flex-wrap items-end gap-2 rounded-xl border bg-card p-4" @submit.prevent="apply"><label class="text-xs">Desde<input v-model="filter.from" type="date" required class="mt-1 block h-9 rounded-md border bg-transparent px-3 text-sm"/></label><label class="text-xs">Hasta<input v-model="filter.to" type="date" required class="mt-1 block h-9 rounded-md border bg-transparent px-3 text-sm"/></label><label v-if="permissions.financial || permissions.operational" class="text-xs">Producto<select v-model="filter.presentation_id" class="mt-1 block h-9 min-w-56 rounded-md border bg-transparent px-3 text-sm"><option value="">Todos los productos</option><option v-for="item in presentations" :key="item.id" :value="item.id">{{ item.name }}</option></select></label><label v-if="people.length && permissions.financial" class="text-xs">Persona<select v-model="filter.person_id" class="mt-1 block h-9 min-w-48 rounded-md border bg-transparent px-3 text-sm"><option value="">Todas las personas</option><option v-for="person in people" :key="person.id" :value="person.id">{{ person.name }}</option></select></label><Button type="submit">Consultar</Button></form>

        <template v-if="business">
            <section><div class="flex items-center gap-2"><h2 class="text-lg font-semibold">Resultado y flujo del negocio</h2><span v-if="business.provisional" class="rounded-full bg-amber-100 px-2 py-1 text-xs text-amber-800">Provisional: existe un mes sin cerrar</span></div><div class="mt-3 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><article class="rounded-xl border bg-card p-4"><small>Flujo de efectivo</small><p class="text-xl font-semibold" :class="business.totals.cash_flow < 0 ? 'text-destructive' : ''">{{ money(business.totals.cash_flow) }}</p><p class="text-xs text-muted-foreground">Entró {{ money(business.totals.cash_in) }} · salió {{ money(business.totals.cash_out) }}</p></article><article class="rounded-xl border bg-card p-4"><small>Resultado económico</small><p class="text-xl font-semibold" :class="business.totals.profit < 0 ? 'text-destructive' : ''">{{ money(business.totals.profit) }}</p><p class="text-xs text-muted-foreground">{{ resultLabel(business.totals.profit) }} · ingresos {{ money(business.totals.revenue) }} · costos/gastos {{ money(business.totals.expenses) }}</p></article><article class="rounded-xl border bg-card p-4"><small>Ventas netas</small><p class="text-xl font-semibold">{{ money(business.totals.sales) }}</p></article><article class="rounded-xl border bg-card p-4"><small>Margen bruto de ventas</small><p class="text-xl font-semibold">{{ money(business.totals.sales_margin) }}</p><p class="text-xs text-muted-foreground">Costo {{ money(business.totals.sales_cost) }}</p></article></div></section>
            <section class="overflow-x-auto rounded-xl border bg-card"><h3 class="p-4 font-semibold">Resultado diario</h3><table class="w-full text-sm"><thead class="border-y bg-muted/40 text-left"><tr><th class="px-4 py-3">Día</th><th class="px-4 py-3">Entradas</th><th class="px-4 py-3">Salidas</th><th class="px-4 py-3">Flujo</th><th class="px-4 py-3">Ingresos</th><th class="px-4 py-3">Costos/gastos</th><th class="px-4 py-3">Resultado</th></tr></thead><tbody class="divide-y"><tr v-for="day in business.daily" :key="day.date"><td class="px-4 py-2">{{ day.date }}</td><td class="px-4 py-2">{{ money(day.cash_in) }}</td><td class="px-4 py-2">{{ money(day.cash_out) }}</td><td class="px-4 py-2">{{ money(day.cash_flow) }}</td><td class="px-4 py-2">{{ money(day.revenue) }}</td><td class="px-4 py-2">{{ money(day.expenses) }}</td><td class="px-4 py-2 font-medium" :class="day.profit < 0 ? 'text-destructive' : day.profit > 0 ? 'text-emerald-700' : ''">{{ resultLabel(day.profit) }} · {{ money(day.profit) }}</td></tr></tbody></table></section>
            <section class="grid gap-5 xl:grid-cols-2"><article class="overflow-x-auto rounded-xl border bg-card"><h3 class="p-4 font-semibold">Margen por producto</h3><table class="w-full text-sm"><thead class="border-y bg-muted/40 text-left"><tr><th class="px-4 py-3">Producto</th><th class="px-4 py-3">Cantidad</th><th class="px-4 py-3">Venta</th><th class="px-4 py-3">Costo</th><th class="px-4 py-3">Margen</th></tr></thead><tbody class="divide-y"><tr v-for="item in margins" :key="item.presentation_id"><td class="px-4 py-3">{{ item.product }} · {{ item.presentation }}</td><td class="px-4 py-3">{{ number(item.quantity, 6) }}</td><td class="px-4 py-3">{{ money(item.sales) }}</td><td class="px-4 py-3">{{ money(item.cost) }}</td><td class="px-4 py-3" :class="item.margin < 0 ? 'text-destructive' : ''">{{ money(item.margin) }} · {{ item.margin_percentage }}%</td></tr><tr v-if="!margins.length"><td colspan="5" class="p-6 text-center text-muted-foreground">Sin ventas en el rango.</td></tr></tbody></table></article><article class="rounded-xl border bg-card"><h3 class="p-4 font-semibold">Cartera y obligaciones actuales</h3><div class="grid grid-cols-2 gap-3 border-y p-4 text-sm"><div><small>Por cobrar</small><strong class="block">{{ money(obligations.receivables_total) }}</strong><span class="text-xs text-destructive">Vencido {{ money(obligations.receivables_overdue) }}</span></div><div><small>Por pagar</small><strong class="block">{{ money(obligations.payables_total) }}</strong><span class="text-xs text-destructive">Vencido {{ money(obligations.payables_overdue) }}</span></div></div><div class="grid gap-3 p-4 sm:grid-cols-2"><div><strong class="text-sm">Cobros pendientes</strong><p v-for="item in obligations.receivables.slice(0,10)" :key="item.id" class="mt-2 flex justify-between text-xs"><span :class="item.is_overdue ? 'text-destructive' : ''">{{ item.document }} · {{ item.person }}<small class="block">{{ item.due_at || 'Sin vencimiento' }}</small></span><span>{{ money(item.balance) }}</span></p><Link href="/receivables" class="mt-3 block text-xs text-amber-700 underline">Ver cartera</Link></div><div><strong class="text-sm">Pagos pendientes</strong><p v-for="item in obligations.payables.slice(0,10)" :key="item.id" class="mt-2 flex justify-between text-xs"><span :class="item.is_overdue ? 'text-destructive' : ''">{{ item.document }} · {{ item.person }}<small class="block">{{ item.due_at || 'Sin vencimiento' }}</small></span><span>{{ money(item.balance) }}</span></p></div></div></article></section>
            <section class="overflow-x-auto rounded-xl border bg-card"><h3 class="p-4 font-semibold">Documentos que explican las cifras</h3><table class="w-full text-sm"><thead class="border-y bg-muted/40 text-left"><tr><th class="px-4 py-3">Fecha</th><th class="px-4 py-3">Documento</th><th class="px-4 py-3">Tipo</th><th class="px-4 py-3">Descripción</th><th class="px-4 py-3 text-right">Impacto</th></tr></thead><tbody class="divide-y"><tr v-for="item in business.documents" :key="`${item.kind}-${item.id}`"><td class="px-4 py-2">{{ item.date }}</td><td class="px-4 py-2 font-medium">{{ item.document }}</td><td class="px-4 py-2">{{ item.kind }}</td><td class="px-4 py-2">{{ item.description }}</td><td class="px-4 py-2 text-right">{{ money(item.amount) }}</td></tr></tbody></table></section>
        </template>

        <template v-if="production && inventory">
            <section><h2 class="text-lg font-semibold">Producción e inventario</h2><div class="mt-3 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><article class="rounded-xl border bg-card p-4"><small>Producciones</small><p class="text-xl font-semibold">{{ production.totals.productions }}</p><p class="text-xs text-muted-foreground">Harina {{ number(production.totals.flour_quantity,6) }} kg</p></article><article class="rounded-xl border bg-card p-4"><small>Rendimiento de masa</small><p class="text-xl font-semibold">{{ production.totals.yield_percentage }}%</p><p class="text-xs text-muted-foreground">Real {{ number(production.totals.actual_dough,6) }} de {{ number(production.totals.expected_dough,6) }} kg</p></article><article class="rounded-xl border bg-card p-4"><small>Merma</small><p class="text-xl font-semibold" :class="production.totals.waste > 0 ? 'text-amber-700' : ''">{{ number(production.totals.waste,6) }} kg</p><p class="text-xs text-muted-foreground">{{ production.totals.waste_percentage }}%</p></article><article class="rounded-xl border bg-card p-4"><small>Inventario valorizado</small><p class="text-xl font-semibold">{{ money(inventory.total_value) }}</p><p class="text-xs text-muted-foreground">Bajos {{ inventory.low_count }} · negativos {{ inventory.negative_count }}</p></article></div></section>
            <section class="overflow-x-auto rounded-xl border bg-card"><h3 class="p-4 font-semibold">Rendimiento, merma y costo por producción</h3><table class="w-full text-sm"><thead class="border-y bg-muted/40 text-left"><tr><th class="px-4 py-3">Producción</th><th class="px-4 py-3">Harina</th><th class="px-4 py-3">Masa esperada / real</th><th class="px-4 py-3">Rendimiento</th><th class="px-4 py-3">Merma</th><th class="px-4 py-3">Costo</th></tr></thead><tbody class="divide-y"><tr v-for="item in production.rows" :key="item.id"><td class="px-4 py-3"><Link :href="`/production/${item.id}`" class="font-medium text-amber-700 underline">{{ item.document }}</Link><small class="block text-muted-foreground">{{ item.recipe }} · {{ item.completed_at }}</small></td><td class="px-4 py-3">{{ number(item.flour_quantity,6) }} kg</td><td class="px-4 py-3">{{ number(item.expected_dough,6) }} / {{ number(item.actual_dough,6) }} kg</td><td class="px-4 py-3">{{ item.yield_percentage }}%</td><td class="px-4 py-3">{{ number(item.waste,6) }} kg</td><td class="px-4 py-3">{{ money(item.total_cost) }}<small class="block">{{ money(item.cost_per_dough_kg) }}/kg</small></td></tr><tr v-if="!production.rows.length"><td colspan="6" class="p-6 text-center text-muted-foreground">Sin producciones completadas.</td></tr></tbody></table></section>
            <section class="overflow-x-auto rounded-xl border bg-card"><h3 class="p-4 font-semibold">Existencias y valorización</h3><table class="w-full text-sm"><thead class="border-y bg-muted/40 text-left"><tr><th class="px-4 py-3">Producto</th><th class="px-4 py-3">Físico</th><th class="px-4 py-3">Reservado</th><th class="px-4 py-3">Disponible</th><th class="px-4 py-3">Costo promedio</th><th class="px-4 py-3">Valor</th></tr></thead><tbody class="divide-y"><tr v-for="item in inventory.rows" :key="item.presentation_id" :class="item.is_negative ? 'bg-red-50 dark:bg-red-950/20' : item.is_low ? 'bg-amber-50 dark:bg-amber-950/20' : ''"><td class="px-4 py-3"><strong>{{ item.item }} · {{ item.presentation }}</strong><small class="block text-muted-foreground">{{ item.sku }}<span v-if="item.is_negative"> · inventario negativo</span><span v-else-if="item.is_low"> · inventario bajo</span></small></td><td class="px-4 py-3">{{ number(item.physical_quantity,6) }} {{ item.unit }}</td><td class="px-4 py-3">{{ number(item.reserved_quantity,6) }}</td><td class="px-4 py-3">{{ number(item.available_quantity,6) }}</td><td class="px-4 py-3">{{ money(item.average_unit_cost) }}</td><td class="px-4 py-3">{{ money(item.value) }}</td></tr><tr v-if="!inventory.rows.length"><td colspan="6" class="p-6 text-center text-muted-foreground">Sin existencias para mostrar.</td></tr></tbody></table></section>
        </template>

        <template v-if="household">
            <section><h2 class="text-lg font-semibold">Estado del hogar</h2><div class="mt-3 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><article class="rounded-xl border bg-card p-4"><small>Presupuesto {{ household.budget.month }}</small><p class="text-xl font-semibold">{{ money(household.budget.available) }}</p><p class="text-xs text-muted-foreground">Presupuestado {{ money(household.budget.budgeted) }} · ejecutado {{ money(household.budget.executed) }}</p></article><article class="rounded-xl border bg-card p-4"><small>Solicitudes pendientes</small><p class="text-xl font-semibold">{{ household.pending_requests }}</p><p class="text-xs text-muted-foreground">{{ money(household.requests_total) }}</p></article><article class="rounded-xl border bg-card p-4"><small>Deudas activas</small><p class="text-xl font-semibold">{{ money(household.debt_balance) }}</p><p class="text-xs text-destructive">{{ household.overdue_installments }} cuotas vencidas</p></article><article class="rounded-xl border bg-card p-4"><small>Ahorro activo</small><p class="text-xl font-semibold">{{ money(household.savings_saved) }}</p><p class="text-xs text-muted-foreground">Objetivo {{ money(household.savings_target) }}</p></article></div></section>
            <section class="grid gap-5 xl:grid-cols-2"><article class="overflow-x-auto rounded-xl border bg-card"><h3 class="p-4 font-semibold">Ejecución presupuestal</h3><table class="w-full text-sm"><thead class="border-y bg-muted/40 text-left"><tr><th class="px-4 py-3">Categoría</th><th class="px-4 py-3">Habitante</th><th class="px-4 py-3">Presupuesto</th><th class="px-4 py-3">Ejecutado</th><th class="px-4 py-3">Disponible</th></tr></thead><tbody class="divide-y"><tr v-for="line in household.budget.lines" :key="line.id"><td class="px-4 py-3">{{ line.category }}</td><td class="px-4 py-3">{{ line.person || 'Compartido' }}</td><td class="px-4 py-3">{{ money(line.budgeted_amount) }}</td><td class="px-4 py-3">{{ money(line.executed_amount) }}</td><td class="px-4 py-3" :class="line.available_amount < 0 ? 'text-destructive' : ''">{{ money(line.available_amount) }}</td></tr><tr v-if="!household.budget.lines.length"><td colspan="5" class="p-6 text-center text-muted-foreground">Sin presupuesto visible para el mes.</td></tr></tbody></table></article><article class="rounded-xl border bg-card"><h3 class="p-4 font-semibold">Solicitudes por atender</h3><div class="divide-y"><div v-for="item in household.requests" :key="item.id" class="flex justify-between gap-3 p-4 text-sm"><span><strong>{{ item.document }} · {{ item.requester }}</strong><small class="block text-muted-foreground">{{ item.status }} · necesaria {{ item.needed_at }}</small></span><strong>{{ money(item.amount) }}</strong></div><p v-if="!household.requests.length" class="p-6 text-sm text-muted-foreground">Sin solicitudes pendientes.</p></div><Link href="/household" class="m-4 inline-block text-sm text-amber-700 underline">Abrir hogar</Link></article></section>
        </template>
    </main>
</template>
