<script setup lang="ts">
import { Head, Link, router } from '@inertiajs/vue3';
import { Plus, Search } from '@lucide/vue';
import { ref } from 'vue';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
type Supplier = { id: string; trade_name: string | null; tax_identifier: string | null; default_payment_term_days: number; is_active: boolean; person: { name: string; document_number: string | null; email: string | null; phone: string | null } };
const props = defineProps<{ suppliers: { data: Supplier[] }; filters: { search: string } }>();
const search = ref(props.filters.search); const apply = () => router.get('/purchasing/suppliers', { search: search.value }, { preserveState: true, replace: true });
</script>
<template><Head title="Proveedores" /><main class="flex flex-1 flex-col gap-5 p-4 md:p-6"><header class="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h1 class="text-2xl font-semibold">Proveedores</h1><p class="text-sm text-muted-foreground">Datos comerciales y condiciones habituales de compra.</p></div><div class="flex gap-2"><Button variant="outline" as-child><Link href="/purchasing/purchases">Compras</Link></Button><Button as-child><Link href="/purchasing/suppliers/create"><Plus /> Nuevo proveedor</Link></Button></div></header><form class="flex max-w-xl gap-2" @submit.prevent="apply"><Input v-model="search" placeholder="Nombre o documento" /><Button type="submit" variant="outline"><Search /> Buscar</Button></form><section class="overflow-x-auto rounded-xl border bg-card"><table class="w-full text-sm"><thead class="border-b bg-muted/40 text-left"><tr><th class="px-4 py-3">Proveedor</th><th class="px-4 py-3">Contacto</th><th class="px-4 py-3">Plazo</th><th class="px-4 py-3">Estado</th><th></th></tr></thead><tbody class="divide-y"><tr v-for="supplier in suppliers.data" :key="supplier.id"><td class="px-4 py-3"><p class="font-medium">{{ supplier.trade_name || supplier.person.name }}</p><p class="text-xs text-muted-foreground">{{ supplier.person.document_number || supplier.tax_identifier || 'Sin identificación' }}</p></td><td class="px-4 py-3">{{ supplier.person.phone || supplier.person.email || '—' }}</td><td class="px-4 py-3">{{ supplier.default_payment_term_days }} días</td><td class="px-4 py-3" :class="supplier.is_active ? 'text-emerald-700' : 'text-muted-foreground'">{{ supplier.is_active ? 'Activo' : 'Inactivo' }}</td><td class="px-4 py-3 text-right"><Link :href="`/purchasing/suppliers/${supplier.id}/edit`" class="font-medium text-amber-700 hover:underline">Editar</Link></td></tr></tbody></table><p v-if="suppliers.data.length === 0" class="p-10 text-center text-sm text-muted-foreground">No hay proveedores para mostrar.</p></section></main></template>
