<?php

return [
    'permissions' => [
        'people.view' => ['Personas', 'Consultar personas'],
        'people.manage' => ['Personas', 'Administrar personas'],
        'users.manage' => ['Identidad', 'Administrar usuarios'],
        'roles.manage' => ['Identidad', 'Administrar roles y permisos'],
        'authorizations.request' => ['Autorizaciones', 'Solicitar autorizaciones'],
        'authorizations.approve' => ['Autorizaciones', 'Aprobar autorizaciones'],
        'catalog.view' => ['Catálogo', 'Consultar catálogo'],
        'catalog.manage' => ['Catálogo', 'Administrar catálogo'],
        'inventory.view' => ['Inventario', 'Consultar inventario'],
        'inventory.adjust' => ['Inventario', 'Ajustar inventario'],
        'inventory.authorize-negative' => ['Inventario', 'Autorizar inventario negativo'],
        'packages.convert' => ['Inventario', 'Armar y desarmar paquetes'],
        'recipes.view' => ['Recetas', 'Consultar recetas'],
        'recipes.manage' => ['Recetas', 'Administrar recetas'],
        'recipes.activate-version' => ['Recetas', 'Activar versiones'],
        'production.view' => ['Producción', 'Consultar producción'],
        'production.manage' => ['Producción', 'Administrar producción'],
        'production.complete' => ['Producción', 'Completar producción'],
        'production.reverse' => ['Producción', 'Revertir producción'],
        'cost-periods.view' => ['Costos', 'Consultar periodos de costos'],
        'cost-periods.manage' => ['Costos', 'Administrar periodos de costos'],
        'cost-periods.close' => ['Costos', 'Cerrar periodos de costos'],
        'cost-periods.reopen' => ['Costos', 'Reabrir periodos de costos'],
        'orders.view' => ['Pedidos', 'Consultar pedidos'],
        'orders.manage' => ['Pedidos', 'Administrar pedidos'],
        'sales.create' => ['Ventas', 'Registrar ventas'],
        'sales.reverse' => ['Ventas', 'Revertir ventas'],
        'prices.manage' => ['Precios', 'Administrar precios'],
        'prices.override' => ['Precios', 'Aplicar precios personalizados'],
        'prices.authorize-below-minimum' => ['Precios', 'Autorizar precio bajo el mínimo'],
        'purchases.manage' => ['Compras', 'Administrar compras'],
        'purchases.receive' => ['Compras', 'Recibir compras'],
        'payables.manage' => ['Finanzas', 'Administrar cuentas por pagar'],
        'receivables.manage' => ['Finanzas', 'Administrar cuentas por cobrar'],
        'cash.open' => ['Caja', 'Abrir caja menor'],
        'cash.operate' => ['Caja', 'Operar caja menor'],
        'cash.close' => ['Caja', 'Cerrar caja menor'],
        'cash.authorize-difference' => ['Caja', 'Autorizar diferencias'],
        'finance.view' => ['Finanzas', 'Consultar finanzas'],
        'finance.manage' => ['Finanzas', 'Administrar finanzas'],
        'household.view-own' => ['Hogar', 'Consultar información propia'],
        'household.view-all' => ['Hogar', 'Consultar hogar consolidado'],
        'household.manage' => ['Hogar', 'Administrar hogar'],
        'fund-requests.create' => ['Hogar', 'Crear solicitudes de fondos'],
        'fund-requests.approve' => ['Hogar', 'Aprobar solicitudes de fondos'],
        'fund-requests.pay' => ['Hogar', 'Pagar solicitudes de fondos'],
        'reports.view-operational' => ['Reportes', 'Consultar reportes operativos'],
        'reports.view-financial' => ['Reportes', 'Consultar reportes financieros'],
        'audit.view' => ['Auditoría', 'Consultar auditoría'],
        'backups.manage' => ['Respaldos', 'Administrar respaldos'],
        'backups.restore' => ['Respaldos', 'Restaurar respaldos'],
        'settings.manage' => ['Configuración', 'Administrar configuración'],
    ],

    'roles' => [
        'owner' => ['Propietario', 'Acceso completo al negocio y hogar.', '*'],
        'administrator' => ['Administrador', 'Administración operativa sin privilegios exclusivos del propietario.', [
            'people.view', 'people.manage', 'users.manage', 'authorizations.approve', 'catalog.view', 'catalog.manage', 'inventory.view',
            'inventory.adjust', 'inventory.authorize-negative', 'packages.convert', 'recipes.view', 'recipes.manage',
            'recipes.activate-version', 'production.view', 'production.manage', 'production.complete', 'production.reverse',
            'cost-periods.view', 'cost-periods.manage', 'cost-periods.close', 'orders.view', 'orders.manage',
            'sales.create', 'sales.reverse', 'prices.manage', 'prices.override', 'prices.authorize-below-minimum',
            'purchases.manage', 'purchases.receive', 'payables.manage', 'receivables.manage', 'cash.open',
            'cash.operate', 'cash.close', 'cash.authorize-difference', 'finance.view', 'finance.manage',
            'fund-requests.approve', 'fund-requests.pay', 'reports.view-operational', 'reports.view-financial', 'audit.view',
        ]],
        'production' => ['Producción', 'Operación de recetas, inventario y producciones.', [
            'people.view', 'catalog.view', 'inventory.view', 'recipes.view', 'production.view', 'production.manage',
            'production.complete', 'cost-periods.view', 'orders.view', 'reports.view-operational', 'authorizations.request',
        ]],
        'sales_cash' => ['Ventas y caja', 'Operación de clientes, pedidos, ventas y caja menor.', [
            'people.view', 'catalog.view', 'inventory.view', 'packages.convert', 'orders.view', 'orders.manage',
            'sales.create', 'prices.override', 'cash.open', 'cash.operate', 'cash.close', 'receivables.manage',
            'reports.view-operational', 'authorizations.request',
        ]],
        'resident' => ['Habitante', 'Acceso limitado a la información propia del hogar.', [
            'household.view-own', 'fund-requests.create',
        ]],
        'viewer' => ['Consulta', 'Acceso de solo lectura asignable.', [
            'people.view', 'catalog.view', 'inventory.view', 'recipes.view', 'production.view', 'orders.view',
            'finance.view', 'reports.view-operational',
        ]],
    ],
];
