<script setup lang="ts">
import { useForm } from '@inertiajs/vue3';
import InputError from '@/components/InputError.vue';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
type Unit = { id: string; code: string; name: string; dimension: string }; type Type = { value: string; label: string };
type ItemData = { code: string; name: string; type: string; base_unit_id: string; minimum_stock: string; allow_negative_stock: boolean; is_active: boolean; notes: string };
const props = defineProps<{ submitUrl: string; method: 'post' | 'put'; units: Unit[]; types: Type[]; initial?: ItemData }>();
const form = useForm<ItemData>({ code: props.initial?.code ?? '', name: props.initial?.name ?? '', type: props.initial?.type ?? 'raw_material', base_unit_id: props.initial?.base_unit_id ?? '', minimum_stock: props.initial?.minimum_stock ?? '0', allow_negative_stock: props.initial?.allow_negative_stock ?? false, is_active: props.initial?.is_active ?? true, notes: props.initial?.notes ?? '' });
const submit = () => form.submit(props.method, props.submitUrl, { preserveScroll: true });
</script>
<template><form class="space-y-6" @submit.prevent="submit"><div class="grid gap-5 md:grid-cols-2"><div class="grid gap-2"><Label>Código</Label><Input v-model="form.code" required /><InputError :message="form.errors.code" /></div><div class="grid gap-2"><Label>Nombre</Label><Input v-model="form.name" required /><InputError :message="form.errors.name" /></div><div class="grid gap-2"><Label>Tipo</Label><select v-model="form.type" class="h-9 rounded-md border bg-transparent px-3 text-sm"><option v-for="type in types" :key="type.value" :value="type.value">{{ type.label }}</option></select><InputError :message="form.errors.type" /></div><div class="grid gap-2"><Label>Unidad base</Label><select v-model="form.base_unit_id" required class="h-9 rounded-md border bg-transparent px-3 text-sm"><option value="" disabled>Selecciona</option><option v-for="unit in units" :key="unit.id" :value="unit.id">{{ unit.name }} ({{ unit.code }})</option></select><InputError :message="form.errors.base_unit_id" /></div><div class="grid gap-2"><Label>Existencia mínima</Label><Input v-model="form.minimum_stock" type="number" min="0" step="any" required /><InputError :message="form.errors.minimum_stock" /></div><div class="flex flex-col gap-3 pt-6"><label class="flex items-center gap-2 text-sm"><input v-model="form.is_active" type="checkbox" class="size-4 accent-amber-700" />Artículo activo</label><label class="flex items-center gap-2 text-sm"><input v-model="form.allow_negative_stock" type="checkbox" class="size-4 accent-amber-700" />Puede solicitar inventario negativo</label></div><div class="grid gap-2 md:col-span-2"><Label>Notas</Label><textarea v-model="form.notes" rows="4" class="rounded-md border bg-transparent px-3 py-2 text-sm" /></div></div><div class="flex justify-end gap-3 border-t pt-5"><Button type="button" variant="outline" as-child><a href="/catalog/items">Cancelar</a></Button><Button type="submit" :disabled="form.processing">Guardar artículo</Button></div></form></template>
