<script setup lang="ts">
import { Head, router, useForm } from '@inertiajs/vue3';
import { computed } from 'vue';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';

type Account = { id:string; code:string; name:string; scope:string; person:string|null; person_id:string|null; balance:number };
type Category = { id:string; name:string; type:'income'|'expense' };
type Person = { id:string; name:string };
type Transaction = { id:string; document_number:string; amount:number; description:string; type:string; type_label:string; date:string; person:string|null; category:string|null; from_account:string|null; to_account:string|null; counts_for_budget:boolean };

const props = defineProps<{ month:string; metrics:{income:number;expenses:number;result:number;available:number}; accounts:Account[]; transactions:Transaction[]; categories:Category[]; people:Person[]; canManage:boolean; canViewAll:boolean; now:string }>();
const money = (value:number) => new Intl.NumberFormat('es-CO', { style:'currency', currency:'COP', maximumFractionDigits:0 }).format(value || 0);
const changeMonth = (event:Event) => router.get('/household', { month:(event.target as HTMLInputElement).value }, { preserveState:true });
const account = useForm({ name:'', scope:'household', person_id:'', opening_balance:0 });
const transaction = useForm({ type:'expense', person_id:'', category_id:'', from_account_id:'', to_account_id:'', occurred_at:props.now, amount:0, description:'', counts_for_budget:true });
const matchingCategories = computed(() => props.categories.filter(category => category.type === transaction.type));
const submitTransaction = () => transaction.post('/household/transactions', { onSuccess:() => transaction.reset('amount', 'description') });
</script>

<template>
    <Head title="Finanzas del hogar" />
    <main class="flex flex-1 flex-col gap-5 p-4 md:p-6">
        <header class="flex flex-wrap items-end justify-between gap-3"><div><h1 class="text-2xl font-semibold">Finanzas del hogar</h1><p class="text-sm text-muted-foreground">{{ canViewAll ? 'Vista consolidada autorizada.' : 'Solo ves tus cuentas y movimientos personales.' }}</p></div><input :value="month" type="month" class="h-9 rounded-md border bg-transparent px-3 text-sm" @change="changeMonth" /></header>
        <section class="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><article class="rounded-xl border bg-card p-4"><small>Dinero disponible</small><p class="text-xl font-semibold">{{ money(metrics.available) }}</p></article><article class="rounded-xl border bg-card p-4"><small>Ingresos del mes</small><p class="text-xl font-semibold text-emerald-700">{{ money(metrics.income) }}</p></article><article class="rounded-xl border bg-card p-4"><small>Gastos del mes</small><p class="text-xl font-semibold">{{ money(metrics.expenses) }}</p></article><article class="rounded-xl border bg-card p-4"><small>Resultado</small><p class="text-xl font-semibold" :class="metrics.result < 0 ? 'text-destructive' : ''">{{ money(metrics.result) }}</p></article></section>
        <section class="rounded-xl border bg-card p-4"><h2 class="font-semibold">Cuentas visibles</h2><div class="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><article v-for="item in accounts" :key="item.id" class="rounded-lg bg-muted/40 p-3 text-sm"><p>{{ item.name }}</p><small class="text-muted-foreground">{{ item.person || 'Compartida del hogar' }}</small><strong class="block">{{ money(item.balance) }}</strong></article><p v-if="!accounts.length" class="text-sm text-muted-foreground">No hay cuentas disponibles.</p></div></section>
        <section v-if="canManage" class="grid gap-5 lg:grid-cols-2"><article class="rounded-xl border bg-card p-5"><h2 class="font-semibold">Crear cuenta</h2><form class="mt-4 grid gap-3" @submit.prevent="account.post('/household/accounts', { onSuccess:() => account.reset() })"><Input v-model="account.name" required placeholder="Nombre de la cuenta"/><select v-model="account.scope" class="h-9 rounded-md border bg-transparent px-3 text-sm"><option value="household">Compartida del hogar</option><option value="personal">Personal</option></select><select v-if="account.scope === 'personal'" v-model="account.person_id" required class="h-9 rounded-md border bg-transparent px-3 text-sm"><option value="">Selecciona habitante</option><option v-for="person in people" :key="person.id" :value="person.id">{{ person.name }}</option></select><Input v-model.number="account.opening_balance" type="number" min="0" placeholder="Saldo inicial"/><Button type="submit" :disabled="account.processing">Crear cuenta</Button></form></article>
            <article class="rounded-xl border bg-card p-5"><h2 class="font-semibold">Registrar movimiento</h2><form class="mt-4 grid gap-3" @submit.prevent="submitTransaction"><select v-model="transaction.type" class="h-9 rounded-md border bg-transparent px-3 text-sm" @change="transaction.category_id=''; transaction.from_account_id=''; transaction.to_account_id='' "><option value="income">Ingreso</option><option value="expense">Gasto</option><option value="transfer">Transferencia interna</option></select><select v-model="transaction.person_id" class="h-9 rounded-md border bg-transparent px-3 text-sm"><option value="">Movimiento compartido</option><option v-for="person in people" :key="person.id" :value="person.id">{{ person.name }}</option></select><select v-if="transaction.type !== 'transfer'" v-model="transaction.category_id" required class="h-9 rounded-md border bg-transparent px-3 text-sm"><option value="">Selecciona categoría</option><option v-for="category in matchingCategories" :key="category.id" :value="category.id">{{ category.name }}</option></select><select v-if="transaction.type !== 'income'" v-model="transaction.from_account_id" required class="h-9 rounded-md border bg-transparent px-3 text-sm"><option value="">Cuenta de origen</option><option v-for="item in accounts" :key="item.id" :value="item.id">{{ item.name }} · {{ money(item.balance) }}</option></select><select v-if="transaction.type !== 'expense'" v-model="transaction.to_account_id" required class="h-9 rounded-md border bg-transparent px-3 text-sm"><option value="">Cuenta de destino</option><option v-for="item in accounts.filter(account => account.id !== transaction.from_account_id)" :key="item.id" :value="item.id">{{ item.name }}</option></select><Input v-model.number="transaction.amount" type="number" min="1" required placeholder="Valor"/><Input v-model="transaction.occurred_at" type="datetime-local" required/><Input v-model="transaction.description" required placeholder="Descripción"/><label v-if="transaction.type === 'expense'" class="flex items-center gap-2 text-sm"><input v-model="transaction.counts_for_budget" type="checkbox"/> Contar en el presupuesto</label><Button type="submit" :disabled="transaction.processing">Registrar movimiento</Button></form></article></section>
        <section class="overflow-x-auto rounded-xl border bg-card"><h2 class="p-4 font-semibold">Movimientos del mes</h2><table class="w-full text-sm"><thead class="border-y bg-muted/40 text-left"><tr><th class="px-4 py-3">Fecha / documento</th><th class="px-4 py-3">Tipo</th><th class="px-4 py-3">Detalle</th><th class="px-4 py-3">Habitante</th><th class="px-4 py-3 text-right">Valor</th></tr></thead><tbody class="divide-y"><tr v-for="item in transactions" :key="item.id"><td class="px-4 py-3"><strong>{{ item.document_number }}</strong><small class="block text-muted-foreground">{{ item.date }}</small></td><td class="px-4 py-3">{{ item.type_label }}</td><td class="px-4 py-3"><strong>{{ item.category || `${item.from_account} → ${item.to_account}` }}</strong><small class="block text-muted-foreground">{{ item.description }}</small></td><td class="px-4 py-3">{{ item.person || 'Compartido' }}</td><td class="px-4 py-3 text-right font-medium" :class="item.type === 'expense' ? 'text-destructive' : item.type === 'income' ? 'text-emerald-700' : ''">{{ money(item.amount) }}</td></tr><tr v-if="!transactions.length"><td colspan="5" class="p-6 text-center text-muted-foreground">Sin movimientos visibles en este mes.</td></tr></tbody></table></section>
    </main>
</template>
