<script setup lang="ts">
import { Head, router, useForm } from '@inertiajs/vue3';
import { computed } from 'vue';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';

type Account = { id:string; code:string; name:string; scope:string; person:string|null; person_id:string|null; balance:number };
type Category = { id:string; name:string; type:'income'|'expense' };
type Person = { id:string; name:string };
type Transaction = { id:string; document_number:string; amount:number; description:string; type:string; type_label:string; date:string; person:string|null; category:string|null; from_account:string|null; to_account:string|null; counts_for_budget:boolean };
type FundRequest = { id:string; document_number:string; amount:number; reason:string; requester:string; requester_person_id:string; source_scope:'business'|'household'; source_label:string; needed_at:string; status:string; status_label:string; source_account:string|null; destination_account:string|null; can_confirm:boolean };
type PaymentAccount = { id:string; name:string; scope:'business'|'household'; balance:number };
type DestinationAccount = { id:string; name:string; person_id:string; person:string|null };

const props = defineProps<{ month:string; metrics:{income:number;expenses:number;result:number;available:number}; accounts:Account[]; transactions:Transaction[]; categories:Category[]; people:Person[]; fundRequests:FundRequest[]; paymentAccounts:PaymentAccount[]; destinationAccounts:DestinationAccount[]; canManage:boolean; canViewAll:boolean; canCreateRequest:boolean; canApproveRequests:boolean; canPayRequests:boolean; now:string }>();
const money = (value:number) => new Intl.NumberFormat('es-CO', { style:'currency', currency:'COP', maximumFractionDigits:0 }).format(value || 0);
const changeMonth = (event:Event) => router.get('/household', { month:(event.target as HTMLInputElement).value }, { preserveState:true });
const account = useForm({ name:'', scope:'household', person_id:'', opening_balance:0 });
const transaction = useForm({ type:'expense', person_id:'', category_id:'', from_account_id:'', to_account_id:'', occurred_at:props.now, amount:0, description:'', counts_for_budget:true });
const matchingCategories = computed(() => props.categories.filter(category => category.type === transaction.type));
const submitTransaction = () => transaction.post('/household/transactions', { onSuccess:() => transaction.reset('amount', 'description') });
const fundRequest = useForm({ requester_person_id:'', source_scope:'household', amount:0, reason:'', needed_at:props.now.slice(0,10) });
const decision = useForm({ notes:'' });
const payment = useForm({ source_account_id:'', destination_account_id:'', paid_at:props.now });
const payRequest = (item:FundRequest) => {
    payment.post(`/household/fund-requests/${item.id}/pay`);
};
</script>

<template>
    <Head title="Finanzas del hogar" />
    <main class="flex flex-1 flex-col gap-5 p-4 md:p-6">
        <header class="flex flex-wrap items-end justify-between gap-3"><div><h1 class="text-2xl font-semibold">Finanzas del hogar</h1><p class="text-sm text-muted-foreground">{{ canViewAll ? 'Vista consolidada autorizada.' : 'Solo ves tus cuentas y movimientos personales.' }}</p></div><input :value="month" type="month" class="h-9 rounded-md border bg-transparent px-3 text-sm" @change="changeMonth" /></header>
        <section class="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><article class="rounded-xl border bg-card p-4"><small>Dinero disponible</small><p class="text-xl font-semibold">{{ money(metrics.available) }}</p></article><article class="rounded-xl border bg-card p-4"><small>Ingresos del mes</small><p class="text-xl font-semibold text-emerald-700">{{ money(metrics.income) }}</p></article><article class="rounded-xl border bg-card p-4"><small>Gastos del mes</small><p class="text-xl font-semibold">{{ money(metrics.expenses) }}</p></article><article class="rounded-xl border bg-card p-4"><small>Resultado</small><p class="text-xl font-semibold" :class="metrics.result < 0 ? 'text-destructive' : ''">{{ money(metrics.result) }}</p></article></section>
        <section class="rounded-xl border bg-card p-4"><h2 class="font-semibold">Cuentas visibles</h2><div class="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><article v-for="item in accounts" :key="item.id" class="rounded-lg bg-muted/40 p-3 text-sm"><p>{{ item.name }}</p><small class="text-muted-foreground">{{ item.person || 'Compartida del hogar' }}</small><strong class="block">{{ money(item.balance) }}</strong></article><p v-if="!accounts.length" class="text-sm text-muted-foreground">No hay cuentas disponibles.</p></div></section>
        <section v-if="canManage" class="grid gap-5 lg:grid-cols-2"><article class="rounded-xl border bg-card p-5"><h2 class="font-semibold">Crear cuenta</h2><form class="mt-4 grid gap-3" @submit.prevent="account.post('/household/accounts', { onSuccess:() => account.reset() })"><Input v-model="account.name" required placeholder="Nombre de la cuenta"/><select v-model="account.scope" class="h-9 rounded-md border bg-transparent px-3 text-sm"><option value="household">Compartida del hogar</option><option value="personal">Personal</option></select><select v-if="account.scope === 'personal'" v-model="account.person_id" required class="h-9 rounded-md border bg-transparent px-3 text-sm"><option value="">Selecciona habitante</option><option v-for="person in people" :key="person.id" :value="person.id">{{ person.name }}</option></select><Input v-model.number="account.opening_balance" type="number" min="0" placeholder="Saldo inicial"/><Button type="submit" :disabled="account.processing">Crear cuenta</Button></form></article>
            <article class="rounded-xl border bg-card p-5"><h2 class="font-semibold">Registrar movimiento</h2><form class="mt-4 grid gap-3" @submit.prevent="submitTransaction"><select v-model="transaction.type" class="h-9 rounded-md border bg-transparent px-3 text-sm" @change="transaction.category_id=''; transaction.from_account_id=''; transaction.to_account_id='' "><option value="income">Ingreso</option><option value="expense">Gasto</option><option value="transfer">Transferencia interna</option></select><select v-model="transaction.person_id" class="h-9 rounded-md border bg-transparent px-3 text-sm"><option value="">Movimiento compartido</option><option v-for="person in people" :key="person.id" :value="person.id">{{ person.name }}</option></select><select v-if="transaction.type !== 'transfer'" v-model="transaction.category_id" required class="h-9 rounded-md border bg-transparent px-3 text-sm"><option value="">Selecciona categoría</option><option v-for="category in matchingCategories" :key="category.id" :value="category.id">{{ category.name }}</option></select><select v-if="transaction.type !== 'income'" v-model="transaction.from_account_id" required class="h-9 rounded-md border bg-transparent px-3 text-sm"><option value="">Cuenta de origen</option><option v-for="item in accounts" :key="item.id" :value="item.id">{{ item.name }} · {{ money(item.balance) }}</option></select><select v-if="transaction.type !== 'expense'" v-model="transaction.to_account_id" required class="h-9 rounded-md border bg-transparent px-3 text-sm"><option value="">Cuenta de destino</option><option v-for="item in accounts.filter(account => account.id !== transaction.from_account_id)" :key="item.id" :value="item.id">{{ item.name }}</option></select><Input v-model.number="transaction.amount" type="number" min="1" required placeholder="Valor"/><Input v-model="transaction.occurred_at" type="datetime-local" required/><Input v-model="transaction.description" required placeholder="Descripción"/><label v-if="transaction.type === 'expense'" class="flex items-center gap-2 text-sm"><input v-model="transaction.counts_for_budget" type="checkbox"/> Contar en el presupuesto</label><Button type="submit" :disabled="transaction.processing">Registrar movimiento</Button></form></article></section>
        <section class="grid gap-5 lg:grid-cols-[minmax(280px,0.7fr)_minmax(0,1.3fr)]"><article v-if="canCreateRequest" class="rounded-xl border bg-card p-5"><h2 class="font-semibold">Solicitar fondos</h2><form class="mt-4 grid gap-3" @submit.prevent="fundRequest.post('/household/fund-requests', { onSuccess:() => fundRequest.reset('amount', 'reason') })"><select v-if="canManage" v-model="fundRequest.requester_person_id" required class="h-9 rounded-md border bg-transparent px-3 text-sm"><option value="">Solicitante</option><option v-for="person in people" :key="person.id" :value="person.id">{{ person.name }}</option></select><select v-model="fundRequest.source_scope" class="h-9 rounded-md border bg-transparent px-3 text-sm"><option value="household">Solicitar al hogar</option><option value="business">Solicitar al negocio como mano de obra</option></select><Input v-model.number="fundRequest.amount" type="number" min="1" required placeholder="Valor solicitado"/><Input v-model="fundRequest.needed_at" type="date" required/><textarea v-model="fundRequest.reason" required maxlength="1000" class="min-h-24 rounded-md border bg-transparent px-3 py-2 text-sm" placeholder="Motivo"></textarea><Button type="submit" :disabled="fundRequest.processing">Enviar solicitud</Button></form></article>
            <article class="overflow-x-auto rounded-xl border bg-card"><h2 class="p-4 font-semibold">Solicitudes de fondos</h2><table class="w-full text-sm"><thead class="border-y bg-muted/40 text-left"><tr><th class="px-4 py-3">Solicitud</th><th class="px-4 py-3">Solicitante</th><th class="px-4 py-3">Valor / origen</th><th class="px-4 py-3">Estado</th><th class="px-4 py-3">Acciones</th></tr></thead><tbody class="divide-y"><tr v-for="item in fundRequests" :key="item.id"><td class="px-4 py-3"><strong>{{ item.document_number }}</strong><small class="block max-w-64 text-muted-foreground">{{ item.reason }} · para {{ item.needed_at }}</small></td><td class="px-4 py-3">{{ item.requester }}</td><td class="px-4 py-3"><strong>{{ money(item.amount) }}</strong><small class="block text-muted-foreground">{{ item.source_label }}</small></td><td class="px-4 py-3">{{ item.status_label }}</td><td class="px-4 py-3"><div class="flex flex-wrap gap-2"><template v-if="item.status === 'requested' && canApproveRequests"><Button size="sm" variant="outline" @click="decision.post(`/household/fund-requests/${item.id}/approve`)">Aprobar</Button><Button size="sm" variant="destructive" @click="decision.post(`/household/fund-requests/${item.id}/reject`)">Rechazar</Button></template><div v-if="item.status === 'approved' && canPayRequests" class="grid min-w-56 gap-2"><select v-model="payment.source_account_id" class="h-8 rounded-md border bg-transparent px-2 text-xs"><option value="">Cuenta de origen</option><option v-for="source in paymentAccounts.filter(account => account.scope === item.source_scope)" :key="source.id" :value="source.id">{{ source.name }} · {{ money(source.balance) }}</option></select><select v-model="payment.destination_account_id" class="h-8 rounded-md border bg-transparent px-2 text-xs"><option value="">Cuenta personal de destino</option><option v-for="destination in destinationAccounts.filter(account => account.person_id === item.requester_person_id)" :key="destination.id" :value="destination.id">{{ destination.name }}</option></select><Input v-model="payment.paid_at" type="datetime-local" class="h-8 text-xs"/><Button size="sm" :disabled="!payment.source_account_id || !payment.destination_account_id || payment.processing" @click="payRequest(item)">Pagar</Button></div><Button v-if="item.can_confirm" size="sm" variant="outline" @click="router.post(`/household/fund-requests/${item.id}/confirm`)">Confirmar recibido</Button></div><small v-if="item.status === 'paid' || item.status === 'confirmed'" class="block text-muted-foreground">{{ item.source_account }} → {{ item.destination_account }}</small></td></tr><tr v-if="!fundRequests.length"><td colspan="5" class="p-6 text-center text-muted-foreground">Sin solicitudes visibles.</td></tr></tbody></table></article></section>
        <section class="overflow-x-auto rounded-xl border bg-card"><h2 class="p-4 font-semibold">Movimientos del mes</h2><table class="w-full text-sm"><thead class="border-y bg-muted/40 text-left"><tr><th class="px-4 py-3">Fecha / documento</th><th class="px-4 py-3">Tipo</th><th class="px-4 py-3">Detalle</th><th class="px-4 py-3">Habitante</th><th class="px-4 py-3 text-right">Valor</th></tr></thead><tbody class="divide-y"><tr v-for="item in transactions" :key="item.id"><td class="px-4 py-3"><strong>{{ item.document_number }}</strong><small class="block text-muted-foreground">{{ item.date }}</small></td><td class="px-4 py-3">{{ item.type_label }}</td><td class="px-4 py-3"><strong>{{ item.category || `${item.from_account} → ${item.to_account}` }}</strong><small class="block text-muted-foreground">{{ item.description }}</small></td><td class="px-4 py-3">{{ item.person || 'Compartido' }}</td><td class="px-4 py-3 text-right font-medium" :class="item.type === 'expense' ? 'text-destructive' : item.type === 'income' ? 'text-emerald-700' : ''">{{ money(item.amount) }}</td></tr><tr v-if="!transactions.length"><td colspan="5" class="p-6 text-center text-muted-foreground">Sin movimientos visibles en este mes.</td></tr></tbody></table></section>
    </main>
</template>
